<?php

/**
 * @file
 * Contains yudl_search.module.
 *
 * This module adds additional search funcationality to YUDL.
 */

use Drupal\search_api\IndexInterface;
use Drupal\search_api\Query\QueryInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yudl_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.yudl_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom search behaviour for YUDL.') . '</p>';
      return $output;
    default:
  }
}
