<?php

/**
 * @file
 * Contains yudl_blocks.module.
 *
 * This module adds YUDL specific blocks.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\search_api\Entity\Index;

/**
 * Implements hook_help().
 */
function yudl_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.yudl_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom blocks for YUDL.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Helper function to format a timestamp as F j, Y.
 *
 * @param DateTime $time
 *   A given timestamp.
 *
 * @return string
 *   Timestamp formatted as F j, Y.
 */
function yudl_blocks_format_time($time) {
  $t = new DateTime();
  $t->setTimestamp(strtotime($time));
  $t->setTimeZone(new DateTimeZone("America/Toronto"));
  return $t->format("F j, Y");
}

/**
 * Helper function to get most recently changed node's last modified date.
 *
 * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager
 *   The entity type manager service.
 *
 * @return time
 *   Return last modified date.
 */
function yudl_blocks_get_latest_changed_node($entityTypeManager) {
  $query = $entityTypeManager->getStorage('node')->getQuery();
  $query->condition('status', 1);
  $query->sort('created', 'DESC');
  $query->range(0, 1);
  $result = $query->execute();
  $node = $result ? $entityTypeManager->getStorage('node')->load(reset($result)) : NULL;
  $last_modified_date = $node ? $node->getCreatedTime() : NULL;
  return yudl_blocks_format_time($last_modified_date);
}

/**
 * Helper function to get count of unique models in a collection.
 *
 * Adapted from from:
 *  https://github.com/asulibraries/islandora-repo/blob/621e4e3fdc180450ae11ccfc41bd472b587ee90b/web
 *  /modules/custom/asu_collection_extras/asu_collection_extras.module.
 *
 * @param int $collection_node
 *   The nid of a given collection.
 *
 * @return array
 *   The number of unique models in a collection, and number of items
 *   in a collection.
 */
function yudl_blocks_solr_get_collection_children($collection_node) {
  $collection_node_id = (is_object($collection_node) ? $collection_node->id() : $collection_node);
  $result_set = [];
  if (!is_null($collection_node_id)) {
    $index = Index::load('default_solr_index');
    $server = $index->getServerInstance();
    $backend = $server->getBackend();
    $solrConnector = $backend->getSolrConnector();
    $solariumQuery = $solrConnector->getSelectQuery();
    $solariumQuery->addParam('q', '((id:*\:node\/' . $collection_node_id . '\:*) OR (itm_field_ancestors:' . $collection_node_id . '))');
    $solariumQuery->setFields(['ds_created', 'sm_field_language']);
    $solariumQuery->addSort('ds_created', 'asc');
    $facetSet = $solariumQuery->getFacetSet();
    $facetSet->createFacetField('model')->setField('itm_field_model');
    $models = [];
    $solariumQuery->setStart(0)->setRows(20000);
    $nids = $solrConnector->execute($solariumQuery);
    $count = $nids->getNumFound();
    if ($count) {
      $result_set['collection_created'] = $nids->getDocuments()[0]->ds_created;
      $result_set['collection_recently_added'] = $nids->getDocuments()[$count - 1]->ds_created;
      $languages_avaliable = array_reduce($nids->getDocuments(), function ($carry, $item) {
        if (isset($item->sm_field_language)) {
          $carry = array_unique(array_merge($carry, array_values($item->sm_field_language)));
        }
        return $carry;
      }, []);
      $result_set['collection_languages'] = count($languages_avaliable);
      $model_facet = $nids->getFacetSet()->getFacet('model');
      foreach ($model_facet as $value => $mod_count) {
        if (!in_array($value, $models)) {
          $models[] = $value;
        }
      }
    }
    $result_set['item_count'] = $count;
    $model_count = count($models);
    $result_set['model_count'] = $model_count;
  }
  else {
    $result_set['collection_created'] = NULL;
    $result_set['collection_recently_added'] = NULL;
  }
  return $result_set;
}
