<?php

/**
 * @file
 * Contains yu_branding.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yu_branding_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the yu_branding module.
    case 'help.page.yu_branding':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides YU header and footer blocks.') . '</p>';
      return $output;

    default:
  }
}
